### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported feature CUSTOM_STORE_API

### ISSUE THREAD

**Issue by maxxer** [ZeXtras/OpenZAL#148]
Release 8.8.15.GA.3869.UBUNTU18.64 UBUNTU18_64 FOSS edition, Patch 8.8.15_P9.

Zal 2.13.0.

When trying to delete a(n empty) volume I get:

```
2020-05-08 15:57:21,864 WARN  [qtp366590980-654:https://10.0.0.69:7071/service/admin/soap/DeleteVolumeRequest] [name=admin@domain.it;mid=1;ip=10.0.0.86;port=
57675;ua=ZimbraWebClient - FF76 (Mac);soapId=3fb1335e;] SoapEngine - handler exception
java.lang.UnsupportedOperationException: Unsupported feature CUSTOM_STORE_API
        at org.openzal.zal.StoreFeature.fromZimbra(StoreFeature.java:72)
        at org.openzal.zal.extension.InternalOverrideStoreManager.supports(InternalOverrideStoreManager.java:105)
        at com.zimbra.cs.service.admin.DeleteVolume.handle(DeleteVolume.java:50)
        at com.zimbra.cs.service.admin.DeleteVolume.handle(DeleteVolume.java:40)
        at org.openzal.zal.soap.InternalOverrideDocumentServiceImpl$1.handleRequest(InternalOverrideDocumentServiceImpl.java:72)
        at com.zextras.modules.admin.proxies.AdminProxy.handleRequest(AdminProxy.java:81)
        at org.openzal.zal.soap.InternalDocumentHelper.handle(InternalDocumentHelper.java:75)
        at org.openzal.zal.soap.InternalOverrideAdminDocumentHandler.handle(InternalOverrideAdminDocumentHandler.java:87)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:646)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:491)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:278)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:308)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:214)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:175)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[...]
```

**Comment by ZextrasGiacomoMattiuzzi** [comment]
Fixed on ZAL 2.15.1
